version: "3.8"
services:
  racing:
    build:
        context: .
        dockerfile: Dockerfile
    image: node
    ports:
      - "80:80"
      - "443:443"
      - "3000:3000"
      - "3001:3001"
    volumes: 
        # - ~/Desktop/dev/tpl:/var/www
        - ./config:/var/www/config
        - ./public:/var/www/public
        - ./tests:/var/www/tests
        - ./cypress.json:/var/www/cypress.json
        - ./jest.config.js:/var/www/jest.config.js
        - ./package.json:/var/www/package.json
        - ./tsconfig.json:/var/www/tsconfig.json
        - ./webpack.config.js:/var/www/webpack.config.js
    networks:
      - racing_network     
networks:
    racing_network:
        driver: bridge