# https://github.com/haugene/docker-transmission-openvpn/blob/master/DockerEnv
# NOTES:
# For referencing transmiison in other containers, since it's behind the VPN you have to use the acutal IP and not the DynDns hostname.
# Calibre web: https://github.com/janeczku/calibre-web/wiki/Configuration

# TODO: Get LL + calibre web talking together
# Update docker-compose to use env vars more
# commit everything

version: "2.0"
services:
  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    networks:
      - plexnet
        #ipv4_address: 192.168.86.27
    env_file: .env
    volumes:
      - ${MOUNT_POINT}/radarr/config:/config
      - ${MOUNT_POINT}/data/completed:/data/completed
      - ${MOUNT_POINT}/plex/Movies:/movies
      # - ~/radar/config:/config
      # - ~/Movies:/movies
      # - ~/Downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
  sonarr:
      image: linuxserver/sonarr:latest
      networks:
        - plexnet
          #ipv4_address: 192.168.86.27
      container_name: sonarr
      env_file: .env
      volumes:
        - ${MOUNT_POINT}/sonarr/config:/config
        - ${MOUNT_POINT}/plex/tv:/tv
        - ${MOUNT_POINT}/data/completed:/data/completed
        # - ~/sonarr/config:/config
        # - ~/TV:/tv
        # - ~/Downloads:/downloads
      ports:
        - 8989:8989
      restart: unless-stopped
  organizr:
    container_name: organizr
    networks:
      - plexnet
        #ipv4_address: 192.168.86.27
    hostname: organizr
    image: organizrtools/organizr-v2:latest
    restart: unless-stopped
    ports:
        - 8085:80
    volumes:
        - ${MOUNT_POINT}/organizr/config:/config
    env_file: .env
  jackett:
    image: linuxserver/jackett:latest
    networks:
      - plexnet
        #ipv4_address: 192.168.86.27
    container_name: jackett
    env_file: .env
    volumes:
      - ${MOUNT_POINT}/jackett/config:/config
      - ${MOUNT_POINT}/jackett/downloads:/downloads
      # - ~/jackett/config:/config
      # - ~/Movies:/movies
      # - ~/Downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
  ombi:
    image: linuxserver/ombi:latest
    container_name: ombi
    networks:
      - plexnet
        #ipv4_address: 192.168.86.27
    env_file: .env
    volumes:
      - ${MOUNT_POINT}/ombi/config:/config
    ports:
      - 3579:3579
    restart: unless-stopped
  calibre-web:
    image: linuxserver/calibre-web:latest
    container_name: calibre-web
    env_file: .env
    volumes:
      - ${MOUNT_POINT}/calibre:/config
      - ${MOUNT_POINT}/data:/data
      - ${MOUNT_POINT}/data/incompletes:/downloads
      - ${MOUNT_POINT}/calibre/books:/books
      - ${MOUNT_POINT}/calibre/magazines:/magazines
      - ${MOUNT_POINT}/calibre/comics:/comics
      - ${MOUNT_POINT}/calibre/audiobooks:/audiobooks
    networks:
      - plexnet
    ports:
      - 8083:8083
    restart: unless-stopped
  lazylibrarian:
    # image: linuxserver/lazylibrarian:latest
    image: thraxis/lazylibrarian-calibre
    container_name: lazylibrarian
    env_file: .env
    volumes:
      - ${MOUNT_POINT}/lazylibrarian/config:/config
      - ${MOUNT_POINT}/calibre:/calibre
      - ${MOUNT_POINT}/data:/data
      - ${MOUNT_POINT}/calibre/books:/books
      - ${MOUNT_POINT}/calibre/comics:/comics
      - ${MOUNT_POINT}/calibre/audiobooks:/audiobooks
      - ${MOUNT_POINT}/calibre/magazines:/magazines
      - ${MOUNT_POINT}/data/incompletes:/downloads/books
      # - ${MOUNT_POINT}/lazylibrarian/downloads:/downloads
    networks:
      - plexnet
    ports:
      - 5299:5299
    restart: unless-stopped
  plex:
    container_name: plex
    image: plexinc/pms-docker:latest
    restart: unless-stopped
    ports:
      - 32323:32323/tcp
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      # - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    env_file: .env
    hostname: lap4178.synology.me
    volumes:
      - ${MOUNT_POINT}/plex:/config
      - ${MOUNT_POINT}/plex/transcode/tmp:/transcode
      - ${MOUNT_POINT}/plex/Movies:/Movies
      - ${MOUNT_POINT}/plex/tv:/tv
      - ${MOUNT_POINT}/plex/Learning:/Learning
      - ${MOUNT_POINT}/plex/AP_Movies:/AP_Movies
      - ${MOUNT_POINT}/plex/kids:/kids
      - ${MOUNT_POINT}/plex:/data
    networks:
      - plexnet
  transmission:
    image: haugene/transmission-openvpn:latest
    container_name: transmission
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: always
    ports:
      - "9091:9091"
      - "8888:8888"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    networks:
      - plexnet
    env_file: .env
    volumes:
      - ${MOUNT_POINT}/data:/data
      - ${MOUNT_POINT}/transmission/openvpn/expressvpn/default.ovpn:/etc/openvpn/custom/default.ovpn
      # - /etc/localtime:/etc/localtime:ro
  proxy:
    image: haugene/transmission-openvpn-proxy
    links:
      - transmission
    env_file: .env
    ports:
      - 8080:8080
    networks:
      - plexnet
  tautulli:
    image: tautulli/tautulli:latest
    restart: unless-stopped
    depends_on:
      - plex
    ports:
      - 8181:8181
    env_file: .env
    volumes:
      - ${MOUNT_POINT}/plex/Library/Application Support/Plex Media Server/Logs/:/plex_logs
      - /volume1/docker/tautulli/config:/config/
  rss:
    image: haugene/transmission-rss
    links:
      - transmission
    env_file: .env
    networks:
      - plexnet
networks:
  plexnet:
    driver: bridge